export const DATEFORMAT = "DD/MM/YYYY";
export const DATETIMEFORMAT = "DD/MM/YYYY HH:mm:ss";

export const ROLES = {
  SUPERADMIN: "SUPERADMIN",
  INSTITUTEADMIN: "INSTITUTEADMIN",
  BRANCHADMIN: "BRANCHADMIN",
  FACULTY: "FACULTY",

  TEACHER: "TEACHER",
};
export const AnsType = {
  SINGLE: "SINGLE",
  MULTIPLE: "MULTIPLE",
  INRANGEANSWER: "INRANGEANSWER",
};

export const EXAMTYPE = {
  OMR: "OMR",
  CBT: "CBT",
};
