export const DATEFORMAT = "DD/MM/YYYY";
export const DATETIMEFORMAT = "DD/MM/YYYY HH:mm:ss";

export const ROLES = {
  SUPERADMIN: "SUPERADMIN",
  INSTITUTEADMIN: "INSTITUTEADMIN",
  BRANCHADMIN: "BRANCHADMIN",
  FACULTY: "FACULTY",

  TEACHER: "TEACHER",
};
