export const authTypes = {
  LOGIN_USER: "LOGIN_USER",

  GET_USER_BY_TOKEN: "GET_USER_BY_TOKEN",

  LOGOUT_USER: "LOGOUT_USER",
};

export const appErrorTypes = {
  GET_APP_ERRORS: "GET_APP_ERRORS",
};

export const settingTypes = {
  GET_SETTING: "GET_SETTING",

  UPDATE_SETTING: "UPDATE_SETTING",
};

export const dashboardTypes = {
  GET_DASHBOARD_DATA: "GET_DASHBOARD_DATA",
};

export const instituteTypes = {
  GET_ALL_INSTITUTES: "GET_INSTITUTES",
  GET_INSTITUTE_BY_ID: "GET_INSTITUTE_BY_ID",

  GET_INSTITUTES: "GET_INSTITUTES",
  ADD_INSTITUTE: "ADD_INSTITUTE",
  UPDATE_INSTITUTE: "UPDATE_INSTITUTE",
  DELETE_INSTITUTE: "DELETE_INSTITUTE",
  BATCH_DELETE_INSTITUTES: "BATCH_DELETE_INSTITUTES",

  SENT_NOTIFICATION: "SENT_NOTIFICATION",
};

export const userTypes = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_USERS: "GET_USERS",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  BATCH_DELETE_USER: "BATCH_DELETE_USER",
};

export const offerTypes = {
  GET_ALL_OFFERS: "GET_ALL_OFFERS",
  GET_OFFERS: "GET_OFFERS",
  ADD_OFFER: "ADD_OFFER",
  UPDATE_OFFER: "UPDATE_OFFER",
  DELETE_OFFER: "DELETE_OFFER",
  BATCH_DELETE_OFFER: "BATCH_DELETE_OFFER",
};

export const currencyTypes = {
  GET_ALL_CURRENCYS: "GET_ALL_CURRENCYS",

  GET_CURRENCYS: "GET_CURRENCYS",
  ADD_CURRENCY: "ADD_CURRENCY",
  UPDATE_CURRENCY: "UPDATE_CURRENCY",
  DELETE_CURRENCY: "DELETE_CURRENCY",
};

export const themeTypes = {
  GET_ALL_THEMES: "GET_ALL_THEMES",

  GET_THEMES: "GET_THEMES",
  ADD_THEME: "ADD_THEME",
  UPDATE_THEME: "UPDATE_THEME",
  DELETE_THEME: "DELETE_THEME",
};

export const categoryTypes = {
  GET_CATEGORYS: "GET_CATEGORYS",
  GET_ALL_CATEGORYS: "GET_ALL_CATEGORYS",

  ADD_CATEGORY: "ADD_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  BATCH_DELETE_CATEGORY: "BATCH_DELETE_CATEGORY",
};

export const dealTypes = {
  GET_DEALS: "GET_DEALS",
  GET_ALL_DEALS: "GET_ALL_DEALS",

  ADD_DEAL: "ADD_DEAL",
  UPDATE_DEAL: "UPDATE_DEAL",
  DELETE_DEAL: "DELETE_DEAL",
  BATCH_DELETE_DEAL: "BATCH_DELETE_DEAL",
};

export const userGroupTypes = {
  GET_USER_GROUPS: "GET_USER_GROUPS",
  GET_ALL_USER_GROUPS: "GET_ALL_USER_GROUPS",

  ADD_USER_GROUP: "ADD_USER_GROUP",
  UPDATE_USER_GROUP: "UPDATE_USER_GROUP",
  DELETE_USER_GROUP: "DELETE_USER_GROUP",
  BATCH_DELETE_USER_GROUP: "BATCH_DELETE_USER_GROUP",
};
export const employeeTypes = {
  GET_EMPLOYEES: "GET_EMPLOYEES",
  GET_ALL_EMPLOYEES: "GET_ALL_EMPLOYEES",

  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  BATCH_DELETE_EMPLOYEE: "BATCH_DELETE_EMPLOYEE",
};

export const instituteServiceTypes = {
  GET_INSTITUTE_SERVICES: "GET_INSTITUTE_SERVICES",
  GET_ALL_INSTITUTE_SERVICES: "GET_ALL_INSTITUTE_SERVICES",

  ADD_INSTITUTE_SERVICE: "ADD_INSTITUTE_SERVICE",
  UPDATE_INSTITUTE_SERVICE: "UPDATE_INSTITUTE_SERVICE",
  DELETE_INSTITUTE_SERVICE: "DELETE_INSTITUTE_SERVICE",
  BATCH_DELETE_INSTITUTE_SERVICE: "BATCH_DELETE_INSTITUTE_SERVICE",
};
export const expenseTypes = {
  GET_EXPENSES: "GET_EXPENSES",
  GET_ALL_EXPENSES: "GET_ALL_EXPENSES",

  ADD_EXPENSE: "ADD_EXPENSE",
  UPDATE_EXPENSE: "UPDATE_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",
  BATCH_DELETE_EXPENSE: "BATCH_DELETE_EXPENSE",
};

export const commonTypes = {
  SET_SELECTED: "SET_SELECTED",

  OPEN_IMAGE_PREVIEW: "OPEN_IMAGE_PREVIEW",

  CLOSE_IMAGE_PREVIEW: "CLOSE_IMAGE_PREVIEW",

  OPEN_NAVBAR: "OPEN_NAVBAR",

  CLOSE_NAVBAR: "CLOSE_NAVBAR",

  OPEN_SIDEBAR: "OPEN_SIDEBAR",

  CLOSE_SIDEBAR: "CLOSE_SIDEBAR",

  SHRINK_SIDEBAR: "SHRINK_SIDEBAR",

  EXPAND_SIDEBAR: "EXPAND_SIDEBAR",
};

export const loadingTypes = {
  ADD_LOADING: "ADD_LOADING",
  REMOVE_LOADING: "REMOVE_LOADING",
};

export const snackTypes = {
  SHOW_SNACKBAR: "SHOW_SNACKBAR",
  HIDE_SNACKBAR: "HIDE_SNACKBAR",
};

export const REQUESTMETHOD = {
  POST: "POST",
  GET: "GET",
  PUT: "PUT",
  PATCH: "PATCH",
  DELETE: "DELETE",
};
