export const authTypes = {
  LOGIN_USER: "LOGIN_USER",

  GET_USER_BY_TOKEN: "GET_USER_BY_TOKEN",

  LOGOUT_USER: "LOGOUT_USER",
  SET_ACTIVE_ROLE: "SET_ACTIVE_ROLE",
};

export const appErrorTypes = {
  GET_APP_ERRORS: "GET_APP_ERRORS",
};

export const settingTypes = {
  GET_SETTING: "GET_SETTING",

  UPDATE_SETTING: "UPDATE_SETTING",
};

export const dashboardTypes = {
  GET_DASHBOARD_DATA: "GET_DASHBOARD_DATA",
};

export const instituteTypes = {
  GET_ALL_INSTITUTES: "GET_INSTITUTES",
  GET_INSTITUTE_BY_ID: "GET_INSTITUTE_BY_ID",

  GET_INSTITUTES: "GET_INSTITUTES",
  ADD_INSTITUTE: "ADD_INSTITUTE",
  UPDATE_INSTITUTE: "UPDATE_INSTITUTE",
  DELETE_INSTITUTE: "DELETE_INSTITUTE",
  BATCH_DELETE_INSTITUTES: "BATCH_DELETE_INSTITUTES",

  SENT_NOTIFICATION: "SENT_NOTIFICATION",
};

export const userTypes = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_USERS: "GET_USERS",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  BATCH_DELETE_USER: "BATCH_DELETE_USER",
};

export const offerTypes = {
  GET_ALL_OFFERS: "GET_ALL_OFFERS",
  GET_OFFERS: "GET_OFFERS",
  ADD_OFFER: "ADD_OFFER",
  UPDATE_OFFER: "UPDATE_OFFER",
  DELETE_OFFER: "DELETE_OFFER",
  BATCH_DELETE_OFFER: "BATCH_DELETE_OFFER",
};

export const currencyTypes = {
  GET_ALL_CURRENCYS: "GET_ALL_CURRENCYS",

  GET_CURRENCYS: "GET_CURRENCYS",
  ADD_CURRENCY: "ADD_CURRENCY",
  UPDATE_CURRENCY: "UPDATE_CURRENCY",
  DELETE_CURRENCY: "DELETE_CURRENCY",
};

export const branchTypes = {
  GET_ALL_BRANCHS: "GET_ALL_BRANCHS",

  GET_BRANCHS: "GET_BRANCHS",
  ADD_BRANCH: "ADD_BRANCH",
  UPDATE_BRANCH: "UPDATE_BRANCH",
  DELETE_BRANCH: "DELETE_BRANCH",
};

export const themeTypes = {
  GET_ALL_THEMES: "GET_ALL_THEMES",

  GET_THEMES: "GET_THEMES",
  ADD_THEME: "ADD_THEME",
  UPDATE_THEME: "UPDATE_THEME",
  DELETE_THEME: "DELETE_THEME",
};

export const categoryTypes = {
  GET_CATEGORYS: "GET_CATEGORYS",
  GET_ALL_CATEGORYS: "GET_ALL_CATEGORYS",

  ADD_CATEGORY: "ADD_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  BATCH_DELETE_CATEGORY: "BATCH_DELETE_CATEGORY",
};

export const subjectTypes = {
  GET_SUBJECTS: "GET_SUBJECTS",
  GET_ALL_SUBJECTS: "GET_ALL_SUBJECTS",

  ADD_SUBJECT: "ADD_SUBJECT",
  UPDATE_SUBJECT: "UPDATE_SUBJECT",
  DELETE_SUBJECT: "DELETE_SUBJECT",
  BATCH_DELETE_SUBJECT: "BATCH_DELETE_SUBJECT",
  IMPORT_SUBJECT: "IMPORT_SUBJECT",
};

export const questionBankTypes = {
  GET_QUESTION_BANKS: "GET_QUESTION_BANKS",
  GET_ALL_QUESTION_BANKS: "GET_ALL_QUESTION_BANKS",

  ADD_QUESTION_BANK: "ADD_QUESTION_BANK",
  UPDATE_QUESTION_BANK: "UPDATE_QUESTION_BANK",
  DELETE_QUESTION_BANK: "DELETE_QUESTION_BANK",
  BATCH_DELETE_QUESTION_BANK: "BATCH_DELETE_QUESTION_BANK",
  IMPORT_QUESTION_BANK: "IMPORT_QUESTION_BANK",
};

export const topicTypes = {
  GET_TOPICS: "GET_TOPICS",
  GET_ALL_TOPICS: "GET_ALL_TOPICS",

  ADD_TOPIC: "ADD_TOPIC",
  UPDATE_TOPIC: "UPDATE_TOPIC",
  DELETE_TOPIC: "DELETE_TOPIC",
  BATCH_DELETE_TOPIC: "BATCH_DELETE_TOPIC",
};

export const subTopicTypes = {
  GET_SUB_TOPICS: "GET_SUB_TOPICS",
  GET_ALL_SUB_TOPICS: "GET_ALL_SUB_TOPICS",

  ADD_SUB_TOPIC: "ADD_SUB_TOPIC",
  UPDATE_SUB_TOPIC: "UPDATE_SUB_TOPIC",
  DELETE_SUB_TOPIC: "DELETE_SUB_TOPIC",
  BATCH_DELETE_SUB_TOPIC: "BATCH_DELETE_SUB_TOPIC",
};

export const qualificationTypes = {
  GET_QUALIFICATIONS: "GET_QUALIFICATIONS",
  GET_ALL_QUALIFICATIONS: "GET_ALL_QUALIFICATIONS",

  ADD_QUALIFICATION: "ADD_QUALIFICATION",
  UPDATE_QUALIFICATION: "UPDATE_QUALIFICATION",
  DELETE_QUALIFICATION: "DELETE_QUALIFICATION",
  BATCH_DELETE_QUALIFICATION: "BATCH_DELETE_QUALIFICATION",
  IMPORT_QUALIFICATION: "IMPORT_QUALIFICATION",
};

export const degreeTypes = {
  GET_DEGREES: "GET_DEGREES",
  GET_ALL_DEGREES: "GET_ALL_DEGREES",

  ADD_DEGREE: "ADD_DEGREE",
  UPDATE_DEGREE: "UPDATE_DEGREE",
  DELETE_DEGREE: "DELETE_DEGREE",
  BATCH_DELETE_DEGREE: "BATCH_DELETE_DEGREE",
};

export const boardTypes = {
  GET_BOARDS: "GET_BOARDS",
  GET_ALL_BOARDS: "GET_ALL_BOARDS",

  ADD_BOARD: "ADD_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  DELETE_BOARD: "DELETE_BOARD",
  BATCH_DELETE_BOARD: "BATCH_DELETE_BOARD",
};

export const goalTypes = {
  GET_GOALS: "GET_GOALS",
  GET_ALL_GOALS: "GET_ALL_GOALS",

  ADD_GOAL: "ADD_GOAL",
  UPDATE_GOAL: "UPDATE_GOAL",
  DELETE_GOAL: "DELETE_GOAL",
  BATCH_DELETE_GOAL: "BATCH_DELETE_GOAL",
  IMPORT_GOAL: "IMPORT_GOAL",
};

export const questionTypes = {
  GET_QUESTIONS: "GET_QUESTIONS",
  GET_ALL_QUESTIONS: "GET_ALL_QUESTIONS",

  ADD_QUESTION: "ADD_QUESTION",
  UPDATE_QUESTION: "UPDATE_QUESTION",
  DELETE_QUESTION: "DELETE_QUESTION",
  BATCH_DELETE_QUESTION: "BATCH_DELETE_QUESTION",
};

export const stateTypes = {
  GET_STATES: "GET_STATES",
  GET_ALL_STATES: "GET_ALL_STATES",

  ADD_STATE: "ADD_STATE",
  UPDATE_STATE: "UPDATE_STATE",
  DELETE_STATE: "DELETE_STATE",
  BATCH_DELETE_STATE: "BATCH_DELETE_STATE",
};
export const testSeriesTypes = {
  GET_TEST_SERIESS: "GET_TEST_SERIESS",
  GET_ALL_TEST_SERIESS: "GET_ALL_TEST_SERIESS",

  ADD_TEST_SERIES: "ADD_TEST_SERIES",
  PUBLISH_TEST_SERIES: "PUBLISH_TEST_SERIES",

  UPDATE_TEST_SERIES: "UPDATE_TEST_SERIES",
  DELETE_TEST_SERIES: "DELETE_TEST_SERIES",
  BATCH_DELETE_TEST_SERIES: "BATCH_DELETE_TEST_SERIES",
};
export const testTypes = {
  GET_TESTS: "GET_TESTS",
  GET_ALL_TESTS: "GET_ALL_TESTS",

  GET_TEST_QUESTIONS: "GET_TEST_QUESTIONS",
  GET_ALL_TEST_QUESTIONS: "GET_ALL_TEST_QUESTIONS",

  ADD_TEST: "ADD_TEST",
  ADD_TEST_QUESTIONS: "ADD_TEST_QUESTIONS",

  UPDATE_TEST: "UPDATE_TEST",
  DELETE_TEST: "DELETE_TEST",
  BATCH_DELETE_TEST: "BATCH_DELETE_TEST",
};
export const languageTypes = {
  GET_LANGUAGES: "GET_LANGUAGES",
  GET_ALL_LANGUAGES: "GET_ALL_LANGUAGES",

  ADD_LANGUAGE: "ADD_LANGUAGE",
  UPDATE_LANGUAGE: "UPDATE_LANGUAGE",
  DELETE_LANGUAGE: "DELETE_LANGUAGE",
  BATCH_DELETE_LANGUAGE: "BATCH_DELETE_LANGUAGE",
};
export const examTypeTypes = {
  GET_EXAM_TYPES: "GET_EXAM_TYPES",
  GET_ALL_EXAM_TYPES: "GET_ALL_EXAM_TYPES",

  ADD_EXAM_TYPE: "ADD_EXAM_TYPE",
  UPDATE_EXAM_TYPE: "UPDATE_EXAM_TYPE",
  DELETE_EXAM_TYPE: "DELETE_EXAM_TYPE",
  BATCH_DELETE_EXAM_TYPE: "BATCH_DELETE_EXAM_TYPE",
};

export const productTypeTypes = {
  GET_PRODUCT_TYPES: "GET_PRODUCT_TYPES",
  GET_ALL_PRODUCT_TYPES: "GET_ALL_PRODUCT_TYPES",

  ADD_PRODUCT_TYPE: "ADD_PRODUCT_TYPE",
  UPDATE_PRODUCT_TYPE: "UPDATE_PRODUCT_TYPE",
  DELETE_PRODUCT_TYPE: "DELETE_PRODUCT_TYPE",
  BATCH_DELETE_PRODUCT_TYPE: "BATCH_DELETE_PRODUCT_TYPE",
};

export const studentTypes = {
  GET_STUDENTS: "GET_STUDENTS",
  GET_ALL_STUDENTS: "GET_ALL_STUDENTS",

  ADD_STUDENT: "ADD_STUDENT",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
  BATCH_DELETE_STUDENT: "BATCH_DELETE_STUDENT",
};

export const dealTypes = {
  GET_DEALS: "GET_DEALS",
  GET_ALL_DEALS: "GET_ALL_DEALS",

  ADD_DEAL: "ADD_DEAL",
  UPDATE_DEAL: "UPDATE_DEAL",
  DELETE_DEAL: "DELETE_DEAL",
  BATCH_DELETE_DEAL: "BATCH_DELETE_DEAL",
};

export const userGroupTypes = {
  GET_USER_GROUPS: "GET_USER_GROUPS",
  GET_ALL_USER_GROUPS: "GET_ALL_USER_GROUPS",

  ADD_USER_GROUP: "ADD_USER_GROUP",
  UPDATE_USER_GROUP: "UPDATE_USER_GROUP",
  DELETE_USER_GROUP: "DELETE_USER_GROUP",
  BATCH_DELETE_USER_GROUP: "BATCH_DELETE_USER_GROUP",
};
export const employeeTypes = {
  GET_EMPLOYEES: "GET_EMPLOYEES",
  GET_ALL_EMPLOYEES: "GET_ALL_EMPLOYEES",

  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  BATCH_DELETE_EMPLOYEE: "BATCH_DELETE_EMPLOYEE",
};

export const instituteServiceTypes = {
  GET_INSTITUTE_SERVICES: "GET_INSTITUTE_SERVICES",
  GET_ALL_INSTITUTE_SERVICES: "GET_ALL_INSTITUTE_SERVICES",

  ADD_INSTITUTE_SERVICE: "ADD_INSTITUTE_SERVICE",
  UPDATE_INSTITUTE_SERVICE: "UPDATE_INSTITUTE_SERVICE",
  DELETE_INSTITUTE_SERVICE: "DELETE_INSTITUTE_SERVICE",
  BATCH_DELETE_INSTITUTE_SERVICE: "BATCH_DELETE_INSTITUTE_SERVICE",
};
export const expenseTypes = {
  GET_EXPENSES: "GET_EXPENSES",
  GET_ALL_EXPENSES: "GET_ALL_EXPENSES",

  ADD_EXPENSE: "ADD_EXPENSE",
  UPDATE_EXPENSE: "UPDATE_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",
  BATCH_DELETE_EXPENSE: "BATCH_DELETE_EXPENSE",
};

export const commonTypes = {
  SET_SELECTED: "SET_SELECTED",

  OPEN_IMAGE_PREVIEW: "OPEN_IMAGE_PREVIEW",

  CLOSE_IMAGE_PREVIEW: "CLOSE_IMAGE_PREVIEW",

  OPEN_NAVBAR: "OPEN_NAVBAR",

  CLOSE_NAVBAR: "CLOSE_NAVBAR",

  OPEN_SIDEBAR: "OPEN_SIDEBAR",

  CLOSE_SIDEBAR: "CLOSE_SIDEBAR",

  SHRINK_SIDEBAR: "SHRINK_SIDEBAR",

  EXPAND_SIDEBAR: "EXPAND_SIDEBAR",

  OPEN_ROLE_SELECTOR: "OPEN_ROLE_SELECTOR",

  CLOSE_ROLE_SELECTOR: "CLOSE_ROLE_SELECTOR",
};

export const loadingTypes = {
  ADD_LOADING: "ADD_LOADING",
  REMOVE_LOADING: "REMOVE_LOADING",
};

export const snackTypes = {
  SHOW_SNACKBAR: "SHOW_SNACKBAR",
  HIDE_SNACKBAR: "HIDE_SNACKBAR",
};

export const REQUESTMETHOD = {
  POST: "POST",
  GET: "GET",
  PUT: "PUT",
  PATCH: "PATCH",
  DELETE: "DELETE",
};
